---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: spring-healthcheck-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: app
          image: alexandreroman/spring-healthcheck-demo
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 8080
          livenessProbe:
            # Liveness probe is used to check if this app is still ready to serve traffic
            # (after it is marked as "ready").
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 60
            periodSeconds: 2
          readinessProbe:
            # Readiness probe is used to check if this app is ready to serve traffic.
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 15
